import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/components/common/Providers";

const montserrat = Montserrat({
	subsets: ["latin"],
	weight: "variable",
	variable: "--font-montserrat",
	display: "swap",
});

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["300", "400", "500", "700"],
	variable: "--font-poppins",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${montserrat.variable} ${poppins.variable} antialiased overflow-x-hidden select-none`}>
				<Providers>{children}</Providers>
				<div id="modal-root"/>
			</body>
		</html>
	);
}
